# Generated by Django 5.0.2 on 2024-02-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_update_datetime", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=140)),
                ("contact_person", models.CharField(max_length=140)),
                ("contact_phone", models.CharField(max_length=15)),
                ("contact_email", models.EmailField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_update_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("description", models.CharField(max_length=256)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="tasks.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Epic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_update_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                ("deadline", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epics",
                        to="tasks.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_update_datetime", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                ("is_done", models.BooleanField(default=False)),
                (
                    "epic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.epic",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tasks.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=140)),
                ("last_name", models.CharField(max_length=140)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=140)),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="skills", to="tasks.skill"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_manager",
                to="tasks.worker",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(related_name="projects", to="tasks.worker"),
        ),
    ]
