# Generated by Django 5.0.2 on 2024-02-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.IntegerField(default=0),
        ),
    ]
