#!/bin/sh

set -o errexit
set -o nounset

# Run django migrate script and set dummy table
django_migrate() {
  echo "*** Running migrate"
  python manage.py migrate --noinput || exit 1
}

django_runserver() {
  echo "Run development webserver"
  python manage.py runserver 0.0.0.0:8000
}

django_migrate
django_runserver
